title: "Master of Pores"
subtitle: ""
intro_text: False

report_header_info:
    - Application Type: 'Nanopore sequencing'

custom_logo: 'logo_small.png'
custom_logo_url: 'https://github.com/biocorecrg/nanopore_analysis'
custom_logo_title: 'Master of Pores'

extra_fn_clean_trim: 
   - '_QC'

table_columns_visible:
    FastQC:
        percent_duplicates: True

module_order:
 - fastqc:
        name: 'FastQC'
        info: 'This section of the report shows FastQC results on raw reads.'

 - alnQC:
        name: "alnQC"
        info: 'This section of the report shows alnQC results on aligned reads' 
