title: "MoP2 - pipeline"
subtitle: ""
intro_text: False

report_header_info:
    - Please cite: "Cozzuto L, Liu H, Pryszcz LP, Pulido TH, Delgado-Tejedor A, Ponomarenko J, Novoa EM. MasterOfPores: A Workflow for the Analysis of Oxford Nanopore Direct RNA Sequencing Datasets. Front Genet. 2020 Mar 17;11:211. doi: 10.3389/fgene.2020.00211"

custom_logo: 'logo_small.png'
custom_logo_url: 'https://github.com/biocorecrg/MoP2'
custom_logo_title: 'Master of Pores 2'

extra_fn_clean_trim: 
   - '_QC'
   - '.count'

read_count_multiplier: 0.001
read_count_prefix: 'K'
read_count_desc: 'thousands'

table_columns_visible:
    FastQC:
        percent_duplicates: True
   
top_modules:
 - fastqc:
        name: 'FastQC'
        info: 'This section of the report shows FastQC results on raw reads.'
 - alnQC:
        name: "alnQC"
        info: 'This section of the report shows alnQC results on aligned reads'
 - minionqc
 - RNA201120181_REP2_bc_1_stats:
        info: 'Nanoplot stats' 
