# Install biocorecrg/htseq:30e9e9c
FROM biocorecrg/centos-perlbrew-pyenv3-java:centos7

# File Author / Maintainer
MAINTAINER Luca Cozzuto <lucacozzuto@gmail.com> 

ARG HTSEQ_VERSION=30e9e9c


#upgrade pip
RUN pip install -U pip

# Installing modules for EPINANO
RUN pip install numpy pysam wheel 
RUN pip install matplotlib 
RUN pip install scipy 
RUN pip install anndata loompy cython
RUN git clone "https://github.com/htseq/htseq.git"; cd htseq; git checkout ${HTSEQ_VERSION}; python setup.py build; python setup.py install



# Clean cache
#RUN yum clean all 

#cleaning
RUN rm -fr htseq 
RUN rm -rf /var/cache/yum

ENV LC_ALL=en_US.utf8
ENV LANG=en_US.utf8

